### ISSUE TITLE
Generell Question 

### ISSUE THREAD

**Issue by eikebartels** [remirobert/Tempo#1]
Hey dude, 

first of all compliment. I really like your library. I have just a general questions.

Why do you not extend NSDate instead of create a own class? I mean then you don't need a function (convertToNSDate) to convert your class to NSDate. Does have that a special reason? 

And could you maybe add cocoapods? 

Cheers, 

Eike

**Comment by remirobert** [comment]
Hi, thanks for all, i will try to add it to cocoaPod. i plained a lot of feature for the library. It will coming soon.

**Comment by eikebartels** [comment]
Awesome! I would like to contribute. Maybe a task list would be sweet? 

And you didn't answer my actually question.

"Why do you not extend NSDate but created a own class instead?"

**Comment by remirobert** [comment]
The first thing to do is to make unit test, for the stability.

**Comment by remirobert** [comment]
You can contact me by mail. It's better. See you.
