### ISSUE TITLE
Inefficient use of NSDateFormatter

### ISSUE THREAD

**Issue by tomassliz** [remirobert/Tempo#2]
Instantiate NSDateFormatter is expensive operation and you use it exactly that way. You can read this in [Apple documentation](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1):

> Creating a date formatter is not a cheap operation. If you are likely to use a formatter frequently, it is typically more efficient to cache a single instance than to create and dispose of multiple instances. One approach is to use a static variable.

**Comment by remirobert** [comment]
good to know thanks, i will probably make a static or a singleton. Thanks !
